-- 更新处理状态枚举类型

-- 添加新的枚举值
ALTER TYPE processingstatus ADD VALUE IF NOT EXISTS 'UPLOADED' BEFORE 'PENDING';
ALTER TYPE processingstatus ADD VALUE IF NOT EXISTS 'SUMMARIZING' AFTER 'PROCESSING';
ALTER TYPE processingstatus ADD VALUE IF NOT EXISTS 'SUMMARIZED' AFTER 'SUMMARIZING';
ALTER TYPE processingstatus ADD VALUE IF NOT EXISTS 'INDEXING' AFTER 'SUMMARIZED';
ALTER TYPE processingstatus ADD VALUE IF NOT EXISTS 'INDEXED' AFTER 'INDEXING';
ALTER TYPE processingstatus ADD VALUE IF NOT EXISTS 'ANALYZING' AFTER 'INDEXED';
ALTER TYPE processingstatus ADD VALUE IF NOT EXISTS 'ANALYZED' AFTER 'ANALYZING';